WINDOWS = "Windows"
UBUNTU = "Ubuntu"
LINUX = "Linux"
OSX = "Darwin"

WEIGHTED_AVG_PAST_WEIGHT = 0.2
WEIGHTED_AVG_CURRENT_WEIGHT = 1 - WEIGHTED_AVG_PAST_WEIGHT

UI_TEXTBOX_REUSED_PASSWORDS = "reused_passwords"
UI_TEXTBOX_UNUSED_ACCOUNTS = "unused_accounts"
UI_TEXTBOX_ACCESS_FREQUENCY = "access_frequency"
UI_TEXTBOX_CHANGE_PASSWORD = "change_password"
UI_TEXTBOX_REPORT_PREVIEW = "preview_report"